### ISSUE TITLE
Inconsistent Klumpy score info

### ISSUE THREAD

**Issue by Myvh** [Lukasdotcom/website#47]
Some Klumpy score rules mouseover info displayed in a game replay are not consistent with the rules stated in the game’s main page (which are consistent with the game itself AFAIK). Here are the erroneous ones:
![image](https://github.com/Lukasdotcom/website/assets/68384832/0fe31fef-c573-492d-b869-f39d519437ae)
![image](https://github.com/Lukasdotcom/website/assets/68384832/a0e26740-0957-47e0-8e28-e35ea9c21744)

**Comment by Lukasdotcom** [comment]
I have removed the info mouseovers while the rules are being finalized.
