### ISSUE TITLE
Klumpy RNG seed problem

### ISSUE THREAD

**Issue by Myvh** [Lukasdotcom/website#48]
When I play Klumpy, I always have the same RNG seed: always the same starting hand and the same following hands if I make the same moves. It is strange but not really an issue by itself. What is more problematic is that not everyone has the same seed: I noticed that another player had a different starting hand in one of their games. Unless I’m missing something, everyone plays a slightly different game given this seed issue, which is counterintuitive given there is a leaderboard.
By the way, thanks for making this little nice game!

**Comment by Lukasdotcom** [comment]
The reason for the game being deterministic was because I was in the process of making daily levels. These daily levels would be an extra leaderboard. I have added a way to play random levels if you choose so now in a button.
